CF = RegisterMod("CF", 1)

require("character.sarah")
require("character.gabriel")
require("character.duster")
require("items.blueberry")
require("items.hiking_boots")
require("items.grease_spray")
require("items.sixd")
require("items.jam")
require("items.aropax")
require("items.DemonHead")
